apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-modifier-webhook-deployment
  labels:
    app: pod-modifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-modifier
  template:
    metadata:
      labels:
        app: pod-modifier
    spec:
      containers:
        - name: pod-modifier
          image: kenbarr/pod-modifier:v1
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: pod-modifier-webhook-certs
