apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-modifier-webhook-cfg
  labels:
    app: pod-modifier
webhooks:
  - name: pod-modifier.solace.com
    clientConfig:
      service:
        name: pod-modifier-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        pod-modifier: enabled
